### ISSUE TITLE
Does not take letter-spacing or word-spacing into account

### ISSUE THREAD

**Issue by arasmussen** [One-com/react-truncate#105] opened 2019-03-21 12:09 UTC
If there's any letter-spacing / word-spacing set on the text, react-truncate will not calculate properly, and it'll render more than `this.props.lines` lines.

Looks like you can set `letter-spacing` / `word-spacing` on the canvas itself https://stackoverflow.com/questions/8952909/letter-spacing-in-canvas-element

Note that the canvas MUST be added to the DOM in order for Chrome to take into account word/letter spacing in its calculations. Probably fine to just add a hidden element somewhere and use it repeatedly.

**Comment by arasmussen** [comment] 2019-03-21 12:11
Here's a working demo: https://jsfiddle.net/zpxh647v/1/

**Comment by PabloSichert** [comment] 2019-04-16 15:27
Duplicate of https://github.com/One-com/react-truncate/issues/59.

Further context: https://github.com/One-com/react-truncate/issues/30#issuecomment-441505843.

If you want to support that in your codebase, I suggest monkey-patching [`Truncate.prototype.measureWidth`](https://github.com/One-com/react-truncate/blob/176e733636a299d6d6c3d730d8f2c26c6580cf91/src/Truncate.js#L171)

**Closed by PabloSichert** 2019-04-16 15:27 UTC
